version: '3'
services:
  ws:
    image: web-server
    hostname: ${APP_HOSTNAME:-ws}
    build:
      context: .
      target: dev
    ports:
      - ${APP_FORWARD_PORT:-80}:${APP_PORT:-8080}
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis-cluster

  redis-1:
    image: 'redis:alpine'
    volumes:
      - ./docker/dev/redis/6371.conf:/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 173.28.0.11
    command:
      - 'redis-server'
      - '/etc/redis/redis.conf'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  redis-2:
    image: 'redis:alpine'
    volumes:
      - ./docker/dev/redis/6372.conf:/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 173.28.0.12
    command:
      - 'redis-server'
      - '/etc/redis/redis.conf'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  redis-3:
    image: 'redis:alpine'
    volumes:
      - ./docker/dev/redis/6373.conf:/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 173.28.0.13
    command:
      - 'redis-server'
      - '/etc/redis/redis.conf'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  redis-4:
    image: 'redis:alpine'
    volumes:
      - ./docker/dev/redis/6374.conf:/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 173.28.0.14
    command:
      - 'redis-server'
      - '/etc/redis/redis.conf'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  redis-5:
    image: 'redis:alpine'
    volumes:
      - ./docker/dev/redis/6375.conf:/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 173.28.0.15
    command:
      - 'redis-server'
      - '/etc/redis/redis.conf'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  redis-6:
    image: 'redis:alpine'
    volumes:
      - ./docker/dev/redis/6376.conf:/etc/redis/redis.conf
    networks:
      redis:
        ipv4_address: 173.28.0.16
    command:
      - 'redis-server'
      - '/etc/redis/redis.conf'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  redis-cluster:
    image: 'redis:alpine'
    networks:
      redis:
        ipv4_address: 173.28.0.17
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    command:
      - 'redis-cli'
      - '--cluster'
      - 'create'
      - '173.28.0.11:6371'
      - '173.28.0.12:6372'
      - '173.28.0.13:6373'
      - '173.28.0.14:6374'
      - '173.28.0.15:6375'
      - '173.28.0.16:6376'
      - '--cluster-yes'
      - '--cluster-replicas'
      - '1'

networks:
  redis:
    ipam:
      config:
        - subnet: '173.28.0.0/17'

volumes:
  cache:
    driver: local
